const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.progressbar.Acts.SetProgress
	];
};
self.C3_JsPropNameTable = [
	{Pontos: 0},
	{Sprite: 0},
	{Plataforma: 0},
	{Ezekiel: 0},
	{Senóide: 0},
	{Mamadeira: 0},
	{Sólido: 0},
	{Grama: 0},
	{Teclado: 0},
	{Pontuação: 0},
	{Áudio: 0},
	{TextoInício: 0},
	{Urso: 0},
	{zonadequeda: 0},
	{Fralda: 0},
	{Vauvau: 0},
	{vocêganhou: 0},
	{Piscar: 0},
	{Fogos: 0},
	{Reiniciar: 0},
	{Plataformafinal: 0},
	{Botão: 0},
	{Tempo: 0},
	{BarraDeProgresso: 0},
	{Finaltempo: 0},
	{Remédio: 0},
	{Temporestante: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Ezekiel: class extends self.ISpriteInstance {},
	Mamadeira: class extends self.ISpriteInstance {},
	Grama: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Pontos: class extends self.ITextInputInstance {},
	Pontuação: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	TextoInício: class extends self.ITextInstance {},
	Urso: class extends self.ISpriteInstance {},
	zonadequeda: class extends self.ISpriteInstance {},
	Fralda: class extends self.ISpriteInstance {},
	Vauvau: class extends self.ISpriteInstance {},
	vocêganhou: class extends self.ITextInstance {},
	Fogos: class extends self.ISpriteInstance {},
	Reiniciar: class extends self.ITextInstance {},
	Plataformafinal: class extends self.ITextInstance {},
	Botão: class extends self.IButtonInstance {},
	BarraDeProgresso: class extends self.IProgressBarInstance {},
	Finaltempo: class extends self.ITextInstance {},
	Remédio: class extends self.ISpriteInstance {}
}